#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jun 03 19:04:17 SAMT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=false
